<?php
return array(
        'advantage'             => 'ADVANTAGE',
        'mines_contact'         => 'MINES CONTACT',
        'mines_select'          => 'STRICT SELECTION PROCESS OF MINERS',
        'mines_select_text'     => 'To fully control the source of risk, MineBit choosesco-operation origanization strictly and does multidimensional audit and credit     evaluation.',
        'mines_manage'          => 'STANDARD MANAGEMENT',
        'mines_manage_text'     => 'Form miner purchase to profit creation,every operation process is under careful control of MineBit to totally ensure the lift cycl    e of the project.',
        'mines_risk_control'    => 'RISK CONTROL',
        'mines_risk_control_text'=> 'The MinBit has its own self-development risk control system for capital selection and invertors will enjoy the agreed income inde    -pendently.',
        'mines_introduce'       => 'INTRODUCE',
        'mines_introduce_text1' => 'The Antminer S9 follows the same dorm factor as that of the hugely popular Antminer S7 and the size is nearly the same as Antminer S7. Yet it has more than thrice the power and twice the efficiency of the S7.Each Antminer S9 employs 189 such chips to deliver more hashrate and effcicncy than any bitcoin miner ever made.',
        'mines_introduce_text2'       => 'The Antminer S9 follows the same dorm factor as that of the hugely popular Antminer S7 and the size is nearly the same as Antminer S7. Yet it has mor    e than thrice the power and twice the efficiency of the S7.Each Antminer S9 employs 189 such chips to deliver more hashrate and effcicncy than any bitcoin miner ever made.',
        'mines_introduce_text3'       => 'The Antminer S9 follows the same dorm factor as that of the hugely popular Antminer S7 and the size is nearly the same as Antminer S7. Yet it has mor    e than thrice the power and twice the efficiency of the S7.Each Antminer S9 employs 189 such chips to deliver more hashrate and effcicncy than any bitcoin miner ever made.',
        'mines_introduce_text4'       => 'The Antminer S9 follows the same dorm factor as that of the hugely popular Antminer S7 and the size is nearly the same as Antminer S7. Yet it has mor    e than thrice the power and twice the efficiency of the S7.Each Antminer S9 employs 189 such chips to deliver more hashrate and effcicncy than any bitcoin miner ever made.The Antminer S9 follows the same dorm factor as that of the hugely popular Antminer S7 and the size is nearly the same as Antminer S7. Yet it has mor    e than thrice the power and twice the efficiency of the S7.Each Antminer S9 employs 189 such chips to deliver more hashrate and effcicncy than any bitcoin miner ever made.The Antminer S9 follows the same dorm factor as that of the hugely popular Antminer S7 and the size is nearly the same as Antminer S7. Yet it has mor    e than thrice the power and twice the efficiency of the S7.Each Antminer S9 employs 189 such chips to deliver more hashrate and effcicncy than any bitcoin miner ever made.',
        'mines_introduce_text5'       => 'The Antminer S9 follows the same dorm factor as that of the hugely popular Antminer S7 and the size is nearly the same as Antminer S7. Yet it has mor    e than thrice the power and twice the efficiency of the S7.Each Antminer S9 employs 189 such chips to deliver more hashrate and effcicncy than any bitcoin miner ever made.The Antminer S9 follows the same dorm factor as that of the hugely popular Antminer S7 and the size is nearly the same as Antminer S7. Yet it has mor    e than thrice the power and twice the efficiency of the S7.Each Antminer S9 employs 189 such chips to deliver more hashrate and effcicncy than any bitcoin miner ever made.The Antminer S9 follows the same dorm factor as that of the hugely popular Antminer S7 and the size is nearly the same as Antminer S7. Yet it has mor    e than thrice the power and twice the efficiency of the S7.Each Antminer S9 employs 189 such chips to deliver more hashrate and effcicncy than any bitcoin miner ever made.',
        'mines_introduce_text6'       => 'The Antminer S9 follows the same dorm factor as that of the hugely popular Antminer S7 and the size is nearly the same as Antminer S7. Yet it has mor    e than thrice the power and twice the efficiency of the S7.Each Antminer S9 employs 189 such chips to deliver more hashrate and effcicncy than any bitcoin miner ever made.',
);
